name: ServerHelper
main: ServerHelper\Main
version: 1.2.0
author: AMDISYES
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
load: STARTUP
commands:
  sh:
    description: "服务器帮助"
    permission: sh.command.player
    usage: /sh <1|2|3|4|5>
  shm:
    description: "管理命令"
    permission: sh.command.op
    usage: /shm <reload|version>
  bread:
    description: "获得面包"
    permission: sh.command.player
permissions:
  sh.command:
    default: true
    description: "根权限"
    children:
      sh.command.player:
        default: true
        description: "玩家权限"
      sh.command.op:
        default: op
        description: "管理权限"